/* eslint-disable react-hooks/immutability, react-hooks/exhaustive-deps */
"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import DashboardLayout from "@/components/dashboard/DashboardLayout";

const labels={participants:"Participants",members:"Competition Members",schedule:"Schedule",payments:"Payments",tickets:"Tickets & QR",attendance:"Attendance"};
export default function OrganizerOperationsPage(){
 const params=useSearchParams(); const view=params.get("view")||"participants"; const [data,setData]=useState(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/organizer/operations").then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[]);
 const title=labels[view]||"Operations";
 if(loading)return <DashboardLayout title={title}><div className="p-10 text-center text-slate-500">Loading {title.toLowerCase()}...</div></DashboardLayout>;
 if(data?.error)return <DashboardLayout title={title}><div className="rounded-3xl border border-red-500/20 bg-red-500/10 p-8 text-red-200">{data.error}</div></DashboardLayout>;
 return <DashboardLayout title={title}><main className="mx-auto max-w-7xl"><header className="mb-8"><p className="text-xs uppercase tracking-[0.2em] text-blue-400">Organizer Operations</p><h1 className="mt-2 text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-400">Live data from your assigned events and competitions.</p></header>{view==="participants"&&<Participants rows={data.registrations}/>} {view==="members"&&<Members rows={data.members} competitions={data.competitions}/>} {view==="schedule"&&<Schedule rows={data.sessions} competitions={data.competitions}/>} {view==="payments"&&<Payments rows={data.payments} registrations={data.registrations}/>} {view==="tickets"&&<Tickets rows={data.registrations}/>} {view==="attendance"&&<Attendance rows={data.attendance} registrations={data.registrations}/>}</main></DashboardLayout>
}
function Table({children}){return <div className="overflow-x-auto rounded-3xl border border-white/10 bg-white/[0.04]"><table className="w-full min-w-[760px] text-left text-sm">{children}</table></div>}
function Participants({rows}){return <Table><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-4">Participant</th><th className="p-4">Competition</th><th className="p-4">College</th><th className="p-4">Registration</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-white/5"><td className="p-4">{r.participant_name||"—"}<div className="text-xs text-slate-500">{r.participant_email}</div></td><td className="p-4">{r.competitions?.name}</td><td className="p-4 text-slate-400">{r.college||"—"}</td><td className="p-4 font-mono text-xs">{r.registration_number}</td><td className="p-4">{r.status}</td></tr>)}</tbody></Table>}
function Members({rows,competitions}){return <Table><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-4">Member</th><th className="p-4">Competition</th><th className="p-4">Assigned</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-white/5"><td className="p-4">{r.profiles?.full_name||r.member_id}</td><td className="p-4">{competitions.find(c=>c.id===r.competition_id)?.name||"—"}</td><td className="p-4">{new Date(r.assigned_at).toLocaleDateString("en-IN")}</td></tr>)}</tbody></Table>}
function Schedule({rows,competitions}){return <Table><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-4">Competition</th><th className="p-4">Session</th><th className="p-4">Date</th><th className="p-4">Time</th><th className="p-4">Venue</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-white/5"><td className="p-4">{competitions.find(c=>c.id===r.competition_id)?.name||"—"}</td><td className="p-4">{r.session_name}</td><td className="p-4">{new Date(`${r.session_date}T00:00:00`).toLocaleDateString("en-IN")}</td><td className="p-4">{r.start_time} – {r.end_time}</td><td className="p-4">{r.venue}</td></tr>)}</tbody></Table>}
function Payments({rows,registrations}){return <Table><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-4">Registration</th><th className="p-4">Amount</th><th className="p-4">Status</th><th className="p-4">Paid</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-white/5"><td className="p-4">{registrations.find(x=>x.id===r.registration_id)?.registration_number||r.registration_id}</td><td className="p-4">₹{Number(r.amount||0).toFixed(2)}</td><td className="p-4">{r.status}</td><td className="p-4">{r.paid_at?new Date(r.paid_at).toLocaleString("en-IN"):"—"}</td></tr>)}</tbody></Table>}
function Tickets({rows}){return <Table><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-4">Participant</th><th className="p-4">Registration</th><th className="p-4">Competition</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-white/5"><td className="p-4">{r.participant_name}</td><td className="p-4 font-mono text-xs">{r.registration_number}</td><td className="p-4">{r.competitions?.name}</td><td className="p-4">{r.status}</td></tr>)}</tbody></Table>}
function Attendance({rows,registrations}){return <Table><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-4">Participant</th><th className="p-4">Registration</th><th className="p-4">Checked In</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map(r=>{const reg=registrations.find(x=>x.id===r.registration_id);return <tr key={r.id} className="border-b border-white/5"><td className="p-4">{reg?.participant_name||"—"}</td><td className="p-4 font-mono text-xs">{reg?.registration_number||"—"}</td><td className="p-4">{new Date(r.checked_in_at).toLocaleString("en-IN")}</td><td className="p-4 text-emerald-300">{r.status}</td></tr>})}</tbody></Table>}
